### ISSUE TITLE
padding issue in pre-training stage

### ISSUE THREAD

**Issue by xixi019** [Yuanhy1997/GenBioEL#3]
Hey,

We're trying to reproduce the result and an error occurs, seemingly with padding. We checked the scripts and could not figure it out.
Below is the error message:
```
RuntimeError: stack expects each tensor to be equal size, but got [1041] at entry 0 and [1024] at entry 1
```

**Comment by Yuanhy1997** [comment]
Can you specify the exact position where the error occurs?

**Comment by xixi019** [comment]
yes, it occurs when we run the script.sh in the GenBioEL/src/kbguided_pretrain. And below I paste a longer error message, it happens in the collate function.

```
01/19/2023 14:41:54 - INFO - utils -   Data Loading Completed for Pretraining Data from ./datagen/tokenized_data/genrated_000.pkl with 922169 samples took 18.95s.
01/19/2023 14:41:54 - INFO - utils -   worker-0: begin epoch 1 current_sample_count 0 shard_length 922169 global_data_samples 0

  0%|          | 0/28816 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/export/home/yan/el/GenBioEL/src/kbguided_pretrain/dataloader.py", line 36, in run
    batch = next(self.dataloaders[dataset_type])
  File "/export/home/yan/el/GenBioEL/src/kbguided_pretrain/dataloader.py", line 252, in <genexpr>
    x
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 146, in collate
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 146, in <listcomp>
    return elem_type([collate(samples, collate_fn_map=collate_fn_map) for samples in transposed])
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/export/home/yan/anaconda3/envs/ent/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1041] at entry 0 and [1024] at entry 1
```

**Comment by Yuanhy1997** [comment]
I think the problem is that some of your generated samples exceed the maximum of 1024 input tokens. I cannot tell how the problem occurs if you follow the generating process for pretraining , while I think an easy fix is your add codes to truncate the input length to be equal and within 1024 length limit.

**Comment by xixi019** [comment]
hey, thanks for reply. We figured out the problem occurs dataloader.py in the pre-tranining dir. there is a mismatch between prefix length led by   this line of code:
```
 y = y[:300]
```
Why do you slice the decoder input (i.e. synonym) to 300?
And why is the encoder input limited to 700?

looking forward to your reply. ^^

**Comment by Yuanhy1997** [comment]
300 and 700 are just randomly set length limits for saving the memory. The consideration is that most of the synonyms in UMLS are of short lengths, however, some concepts concatenated with definitions or other synonyms such as some chemicals may result in thousands of tokens after BPE by BART tokenizer. This will lead to a large batch of tokens and OOM. You can adjust both numbers to fit your own settings.

**Comment by xixi019** [comment]
Got it. In our case I'll just remove this.

**Comment by xixi019** [comment]
fixed
