### ISSUE TITLE
missing file for fine-tuning

### ISSUE THREAD

**Issue by xixi019** [Yuanhy1997/GenBioEL#5]
Hey,

I have finished pre-training and now test the model on fine-tuning tasks.
I followed the instructions, put the preprocessed data in ./src folder and run the create_trie_and_target_kb.py script.
When I execute the train_ask.sh file, it complains a missing file. Below I paste the error message.
```
Setting no soft prompts!
Traceback (most recent call last):
  File "./train.py", line 508, in <module>
    train(config)
  File "./train.py", line 95, in train
    evaluate = config.evaluation,
  File "/export/home/yan/el/GenBioEL/src/datagen/datageneration_finetune.py", line 119, in prepare_trainer_dataset
    encode_data_to_json(os.path.join(text_path, 'train'), tokenizer)
  File "/export/home/yan/el/GenBioEL/src/datagen/datageneration_finetune.py", line 45, in encode_data_to_json
    with open(fi[1]+'.token.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../benchmark/aap/fold0/train.target.token.json'
```

Looking forward to your reply,
Best,
Xixi

**Comment by Yuanhy1997** [comment]
It is not a missing file, you have to run 'mkdir -p ../benchmark/aap/fold0/' to create that directory before training. The line that prompts the error is to create the tokenized training files.
